language: java

before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/plantuml.jar
  - hg clone -r 8.6.7 https://asciidoc.googlecode.com/hg/ asciidoc-8.6.7
language: java

before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.3.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.3/bin/
  
script:
  - java -version
  - javac -version
  - python -V
  - phantomjs -v
  - python asciidoc-8.6.7/asciidoc.py --version
  - dot -V
  - casperjs --version
  - echo Hello from DUT INFO Blagnac
  - ls -alF



  - cd sprint_5

  - echo "COMPILATION de la librairie"


  - javac -cp .;./bin -d ./bin ./src/donnees/*.java
  - javac -cp .;./bin;./tools/junit.jar -d ./bin ./src/Tests/*.java

  
  - echo "Exécution des Tests"


  - cd ./bin
  - java -cp .;../bin;../tools/junit.jar junit.textui.TestRunner Tests.EtudiantTest
  - java -cp .;../bin;../tools/junit.jar junit.textui.TestRunner Tests.IntervenantTest
  - java -cp .;../bin;../tools/junit.jar junit.textui.TestRunner Tests.GroupeTest
  - java -cp .;../bin;../tools/junit.jar junit.textui.TestRunner Tests.ProjetTest
  -  java -cp .;../bin;../tools/junit.jar junit.textui.TestRunner Tests.ParticipationTest
  - java -cp .;../bin;../tools/junit.jar junit.textui.TestRunner Tests.SujetTest
 
  - cd sprint_5
  - java -cp .;./bin;./data;./tools/junit.jar junit.textui.TestRunner Tests.IOToolTest



  - echo "COMPILATION de l'application WEB"


  - javac -cp .;./bin -d ./bin ./src/web/MakeOPTIweb.java



  - echo "Création de la page WEB"


  - java -cp  .;./bin;./data; web.MakeOPTIweb




  - echo "COMPILATION de l'IHM"


  - javac -cp .;./bin -d ./bin ./src/interfacv1/Intervenant.java
  - javac -cp .;./bin -d ./bin ./src/interfacv1/AssProjet.java
  - javac -cp .;./bin -d ./bin ./src/interfacv1/SaisieVoeux.java
  - javac -cp .;./bin -d ./bin ./src/interfacv1/Etudiant.java
  - javac -cp .;./bin -d ./bin ./src/interfacv1/Projet.java
  - javac -cp .;./bin -d ./bin ./src/interfacv1/Groupe.java
  - javac -cp .;./bin -d ./bin ./src/interfacv1/Sujet.java
  - javac -cp .;./bin -d ./bin ./src/interfacv1/APropos.java
  - javac -cp .;./bin -d ./bin ./src/interfacv1/InterfaceLog.java



  - echo "///////////////////////////////////////////////////////"
  - echo "// EXECUTION de l'IHM"
  - echo "///////////////////////////////////////////////////////"

  - java -cp  .;./bin;./data; ./src/interfacv1/InterfaceLog
  - javac -cp .:./bin -d ./bin ./src/HelloMonde.java
  - javac -cp .:./bin:../junit.jar -d ./bin ./src/HelloMondeTest.java
  - java -jar ../plantuml.jar -Tpng -o srcdoc/images srcdoc/diag0.puml
  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o srcdoc/presentationFinale.html srcdoc/presentationFinale.txt
  - ls -alF srcdoc
  - cd bin
  - java -cp .:../../junit.jar HelloMondeTest
  - cd ../OPTIweb/test
  - cp OPTIwebprof.html /tmp/OPTIweb.html
  - casperjs test casperAccueil.js
  
 
 